name: Deploy
on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
jobs:
  sucking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${{ secrets.mail }}
          git config --global user.name ${{ secrets.username }}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
      # Cleanup The Actions Workspace Using Custom Composite Run Actions
      - name: Clone The Secret Mirror Repository
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.url }} -b ${Branch} source
      - name: Compile The Mirroring Docker Container
        run: |
          cd source || exit 1
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t hmm
          docker image ls
      - name: running Docker
        timeout-minutes: 340
        continue-on-error: true
        run: |
          docker run --privileged --rm -i hmm
      - name: ok doit again
        continue-on-error: true
        run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow : Loop"
          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
